#!/bin/bash
bash dependences
mkdir /tmp/.wolfaya
cp -arvf * /tmp/.wolfaya/
cp -arvf /tmp/.wolfaya/ ~/
chmod 733 ~/.wolfaya/wolfaya.py
echo "PATH=$PATH:~/.wolfaya/" >> ~/.bashrc
echo "alias wolfaya='python ~/.wolfaya/wolfaya.pyc'" >>~/.bashrc
rm -rvf /tmp/.wolfaya
echo ""
echo "    -->installed<--"
echo "   restart terminal"
echo "    use cmd 'wolfaya'"
